services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: fastapi_backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      VC_DB_URL: ${VC_DB_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: ["./wait-for-db.sh", "db", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
